// Regenerates public/firebase-messaging-sw.js with the real
// NEXT_PUBLIC_FIREBASE_* values before each build/dev run. The service
// worker is a plain static file served from /public, so it can't read
// process.env like the rest of the app — this is the standard workaround
// for firebase-admin's web SDK + Next.js.
const fs = require('fs');
const path = require('path');

const vars = [
  'NEXT_PUBLIC_FIREBASE_API_KEY',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'NEXT_PUBLIC_FIREBASE_APP_ID',
];

const missing = vars.filter((v) => !process.env[v]);
if (missing.length) {
  console.warn(
    `[firebase-sw] Skipping service worker generation — missing env vars: ${missing.join(', ')}. ` +
    `Push notifications will be disabled until these are set.`
  );
  process.exit(0);
}

const config = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

const contents = `// AUTO-GENERATED by scripts/generate-fcm-sw.js — do not edit directly.
// Regenerated on every dev/build run from NEXT_PUBLIC_FIREBASE_* env vars.
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || 'HomeServe';
  const options = {
    body: payload.notification?.body,
    icon: '/file.svg',
    data: payload.data,
  };
  self.registration.showNotification(title, options);
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.bookingId
    ? \`/bookings/\${event.notification.data.bookingId}\`
    : '/notifications';
  event.waitUntil(clients.openWindow(url));
});
`;

fs.writeFileSync(path.join(__dirname, '..', 'public', 'firebase-messaging-sw.js'), contents);
console.log('[firebase-sw] Generated public/firebase-messaging-sw.js');
